### ISSUE TITLE
[Proposal] — Include licenses in software packages

### ISSUE THREAD

**Issue by flexseth** [WordPress/block-development-examples#107]
# TODO
- [x] Awaiting feedback on proposal
- [x] Add LICENSE files to existing repos
- [x] Figure out workflow for including licenses automatically in the future

# Background

Examples in this repo represent a starting point for code that is open source, but no license is explicitly provided.

If someone adapts part of the repo, works on it, and then ships code or includes it in a public repository, they are offering the software up without a license. 

The GPL covers WordPress Core files, but there isn't a license defined by default in the `plugins` folder - where many of these modules may be found or iterated on. 

## Proposal 
Introduce the idea of licensing in the block development examples repo.

## The why

As software developers level up their skills, ultimately it would be good to know about licensing of proprietary software. The `Block Development Examples` repo offers boilerplate code for developers to learn and build software out, so it's possible to also introduce the idea of how they should expect their clients to be able to use and re-distribute the software. 

Setting expectations for what future users, contributors and collaborators, should be able to do and expect of the software. 

> Use, modify, re-distribute - etc.... 

Some packages include a license in their manifest, such as the [SlotFill example](https://github.com/WordPress/block-development-examples/blob/1d96ae1976bf0ed42fbe772a3cb98fa740117a61/plugins/slotfill-2fb190/slotfill-2fb190.php#L8)

However, no license file is provided in the codebase for this example.

## Licensing use cases
Contributor builds the packages via the provided `pnpm` workflow
- a standard license could be included via the scaffolded files
- use the same license that applies to WordPress Core (GPL v2+)

Using an individual block/plugin
- request / require (via the "new" workflow) - a license to be bundled with the software example

[WordPress's license](https://wordpress.org/about/license/)

Please let me know your feedback!

**Comment by juanmaguitar** [comment]
Thanks for this proposal @flexseth! 
I agree with the idea of adding to this this repo the [same license than WordPress has](https://wordpress.org/about/license/)  `GNU General Public License v2`
AFAIK this could be as simple as adding a `LICENSE` file ([like `wordpress-playground` repo has](https://github.com/WordPress/wordpress-playground/blob/trunk/LICENSE)) to the root of the repo.
I think we can leave this conversation open a few more days and if there are no major objections by anyone from the community we can open a PR to upload a `LICENSE` file to the repo. How does that sound?

**Comment by ndiego** [comment]
> AFAIK this could be as simple as adding a LICENSE file

Yeah, this should do it. I agree, let's add it.

**Comment by flexseth** [comment]
Alright sounds great, I'll leave the issue open for discussion a couple more days. Then will take a look at the best way to include a [GPL v3.0 or later](https://www.gnu.org/licenses/gpl-3.0.en.html) license in the various existing repos, and an updated workflow for automatically adding the license to future packages. 

TODO list added to the issue report for tracking

**Comment by flexseth** [comment]
PR
- https://github.com/WordPress/block-development-examples/pull/119

Commits kept sneaking in to the other branches, I've got to figure out why it's working that way.

**Comment by flexseth** [comment]
Thanks for the comments and review, @ndiego + @juanmaguitar 🙌

Closing - done.
