### ISSUE TITLE
Create "how-to-guides-block-tutorial-XXXXXX"

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/block-development-examples#43]
This should a multi-block plugin containing [all the JSX `gutenberg-examples` referenced in the tutorial](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+path%3A%2F%5Edocs%5C%2Fhow-to-guides%5C%2Fblock-tutorial%5C%2F%2F+gutenberg-examples&type=code):

I would just migrate the JSX examples and would skip for now the NON-JSX examples 

- [ ] `01-basic-esnext` → https://github.com/wptrainingteam/wp-block-development-examples/issues/31
- [ ] `02-stylesheets` → there's no JSX example for this part but I think we should recreate [02-stylesheets](https://github.com/WordPress/gutenberg-examples/tree/trunk/blocks-non-jsx/02-stylesheets) in JSX version 
- [ ] `03-editable-esnext` → https://github.com/wptrainingteam/wp-block-development-examples/issues/33
- [ ] `04-controls-esnext` → https://github.com/wptrainingteam/wp-block-development-examples/issues/34
- [ ] `05-recipe-card-esnext` → https://github.com/wptrainingteam/wp-block-development-examples/issues/35
- [ ] `06-inner-blocks-esnext` → https://github.com/wptrainingteam/wp-block-development-examples/issues/36
- [ ] `08-block-supports-esnext` → https://github.com/wptrainingteam/wp-block-development-examples/issues/38
- [ ] `10-dynamic-block` → https://github.com/wptrainingteam/wp-block-development-examples/issues/40
 
```
├── blocks-jsx
│   ├── 01-basic-esnext
│   ├── 03-editable-esnext
│   ├── 04-controls-esnext
│   ├── 05-recipe-card-esnext
│   ├── 06-inner-blocks-esnext
│   ├── 08-block-supports-esnext
│   ├── 10-dynamic-block
│   └── meta-block
```

**Comment by juanmaguitar** [comment]
Sorry about the confusion.
I thought these examples were part of a larger tutorial and that they were more interconnected (each example was built on top of the previous one), but after a close look at them I realize they're completely isolated examples, so I think the initial approach of having them independently is the best one.
