### ISSUE TITLE
Interactivity API - Countdown Block - broken w/out Gutenberg plugin active

### ISSUE THREAD

**Issue by flexseth** [WordPress/block-development-examples#90]
## Explanation: Requires Gutenberg
[Plugin requires header](https://github.com/WordPress/wordpress-develop/blob/7d606a30e2f475ee434abadff7271205766157d8/src/wp-includes/class-wp-plugin-dependencies.php#L16)

✅ [How to use the header](https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/#:~:text=New%20Plugin%20Header,php%20is%20not%20supported)

### Todo
- [x] Find how to require a plugin in the header
```php
Requires Plugins: gutenberg
```
- [x] Include the Gutenberg plugin as a requirement if necessary for these blocks
- [x] Update plugin header for [Interactivity API Countdown](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/interactivity-api-countdown-3cd73e)
- [X] Update [plugin headers](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/) documentation in the Plugin Handbook

## Background
The Interactivity API won't work without the Gutenberg Plugin active. There's a new header that will throw an error in the dashboard for this (as of 6.5). Trying to get word on this header so it can be documented. 

## How was it discovered?
The [Playground demo](https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/WordPress/block-development-examples/trunk/plugins/interactivity-api-countdown-3cd73e/_playground/blueprint.json) worked, so the code wasn't broken. 

[raw blueprint file](https://raw.githubusercontent.com/WordPress/block-development-examples/trunk/plugins/interactivity-api-countdown-3cd73e/_playground/blueprint.json)

```JSON
{
        "step": "installPlugin",
        "pluginZipFile": {
          "resource": "wordpress.org/plugins",
          "slug": "gutenberg"
        }
```

## Error track
from console
```JS
Uncaught TypeError: Cannot read properties of undefined (reading 'startCountdown')
    at interactivity.min.js?ver=6.5:2:25942
    at Array.forEach (<anonymous>)
    at interactivity.min.js?ver=6.5:2:25927
    at interactivity.min.js?ver=6.5:2:25951
    at interactivity.min.js?ver=6.5:2:29636
    at Object.__ (interactivity.min.js?ver=6.5:2:27702)
    at vt (interactivity.min.js?ver=6.5:2:13563)
    at Array.forEach (<anonymous>)
    at at (interactivity.min.js?ver=6.5:2:12275)
```

## Steps to reproduce
- Clone the repo
- Move blocks from `/plugins` to `/wp-content/plugins` in your installation
- Install packages
- Run build
- Insert interactive countdown block
- No countdown

## Possible culprits
- 👋 Gutenberg not installed?
- 🚫 interactivity API dependencies in package-lock.json?
- 🚫 viewScript changes?
- ⁇ No data from datastore?

**Comment by flexseth** [comment]
closing, fixed by PR
- https://github.com/WordPress/block-development-examples/pull/94

@ryanwelcher - please review!
