### ISSUE TITLE
meta-block-bb1e55: Improve example

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/block-development-examples#97]
- [ ] Improve WP Playground by showing the block inserted with some text
- [ ] Also improve the description of the example
- [ ] Maybe show the content of `wp_postmeta` in the post
- [ ] Add [Step 3: Use post meta data](https://developer.wordpress.org/block-editor/how-to-guides/metabox/#step-3-use-post-meta-data)
